name: Vue Workflow

on:
  workflow_dispatch: 
  schedule:
    - cron: '15 19 * * 1' 
    - cron: '0 0 * * *'    
  push:
    branches:
      - 'features/*'       
      - 'feature/*'        
      - 'release/*'        

jobs:
  test:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' 

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          npm install

      - name: Ejecutar pruebas
        run: |
          npm run test

  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' }

    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Instalar dependencias
        run: |
          npm install

      - name: Construir la aplicación
        run: |
          npm run build

  deploy:
    runs-on: ubuntu-latest
    if: github.event_name != 'schedule' 
    steps:
      - name: Checkout código
        uses: actions/checkout@v2

      - name: Desplegar la aplicación
        if: ${{ startsWith(github.ref, 'refs/heads/release/') }}
        run: |
          echo "Deployando....."

      - name: Notificar éxito
        if: success()
        run: |
          echo "Flujo de trabajo completado exitosamente"
